name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverate:
      name: Code Coverage
      runs-on: ubuntu
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Code Coverage
        run: npm run code-coverage
        continue-on-error: true

      - name: Archive Code Coverage Result
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

# 1) Create a new branch from the main and name it feature/workflow and switch to it

# A workflow should be triggered. Check that it fails in the unit testing step.
# 2) Work on the feature/workflow branch, add the following environment variables at the workflow level:
# MONGO_URI: ‘mongodb+srv://supercluster.d83jj.mongodb.net/superData'
# MONGO_USERNAME: superuser
# MONGO_PASSWORD: SuperPassword
# For MONGO_PASSWORD, add it as a Repository Secret and refer it in the workflow environment variables
# 3) Trigger the workflow and check that it runs successfully

# Currently, the Archive test reports step only run when the previous step are successfully completed.
# Modify the step to execute even when any of the previous steps result in failure.

# Append a new job with id as code-coverage,
# a. This job should execute on this operating system - ubuntu-latest
# b. Add following steps
# Step 1 - use an action to checkout the repository
# Step 2 - use actions/setup-node action to setup NodeJS of version 18
# Step 3 - Install NodeJS dependencies
# Step 4 - Run Code-coverage command (npm run code-coverage)
# This step may fail, configure the step to prevent the job from failing when this step fails.
# Step 5 - Upload code-coverage reports using upload-artifact action with the below
# config
# - name: Code-Coverage-Result
# - path: coverage
# - retention-days: 5